# Generated by Django 3.1.7 on 2021-04-20 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phylum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phylum_name', models.TextField(blank=True)),
                ('phylum_introduction', models.TextField(blank=True)),
                ('phylum_image', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True)),
                ('last_name', models.TextField(blank=True)),
                ('grade', models.TextField(blank=True)),
                ('country', models.TextField(blank=True)),
                ('birth_date', models.DateField(blank=True)),
                ('reg_time', models.DateTimeField(blank=True, default='')),
                ('email_address', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.TextField(blank=True)),
                ('class_introduction', models.TextField(blank=True)),
                ('class_image', models.URLField(blank=True)),
                ('update_time', models.DateTimeField(blank=True)),
                ('phylum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.phylum')),
                ('update_user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project.userprofile')),
            ],
        ),
    ]
