# Generated by Django 3.1.7 on 2021-04-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_class_update_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
