# Generated by Django 3.1.7 on 2021-04-25 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20210425_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='phylum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.phylum'),
        ),
    ]
