# Generated by Django 3.1.7 on 2021-04-25 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20210425_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='update_user',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='project.userprofile'),
        ),
    ]
