# Generated by Django 3.1.7 on 2021-04-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20210425_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='portrait',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
