# Generated by Django 3.1.7 on 2021-03-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0002_statusmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.TextField(blank=True),
        ),
    ]
